language: java
env:
  - MAVEN_VERSION=3.3.9
  - MAVEN_VERSION=3.5.4
  - MAVEN_VERSION=3.6.0
jdk:
  - openjdk7
  - openjdk8
  - openjdk11
install:
  - "mvn --show-version --errors --batch-mode validate dependency:go-offline"
script: "mvn --show-version --errors --batch-mode clean verify"
cache:
    directories:
    - $HOME/.m2
branches:
    except:
        - gh-pages
notifications:
    email:
        - mfriedenhagen@apache.org
        - khmarbaise@apache.org
